### ISSUE TITLE
About samtools invalid option in tigmint-make arcs mode

### ISSUE THREAD

**Issue by ClarenceHsiang** [bcgsc/tigmint#101]
Dear Tigmint team:

I attached the Tigmint by using conda. When I run tigmint-make arcs by using 10X-linked reads, it showed the invalid option in samtools.

Could you give me some suggestions for solving the problem?

Thank you very much.

-------------------------
(Python3_6) [hsiang@pomology-serverIII 01_scaffolding_by_wgs]$ tigmint-make arcs draft=myassembly reads=myreads
bwa mem -t8 -pC myassembly.fa myreads.fq.gz | samtools view -u -F4 | samtools sort -@8 -tBX -T$(mktemp -u -t myassembly.myreads.sortbx.bam.XXXXXX) -o myassembly.myreads.sortbx.bam
sort: invalid option -- 't'
sort: invalid option -- 'B'
sort: invalid option -- 'X'
sort: invalid option -- 'T'
sort: invalid option -- '/'
sort: invalid option -- 't'

Usage:   samtools sort [options] <in.bam> <out.prefix>
Options: -n        sort by read name
         -f        use <out.prefix> as full file name instead of prefix
         -o        final output to stdout
         -l INT    compression level, from 0 to 9 [-1]
         -@ INT    number of sorting and compression threads [1]
         -m INT    max memory per thread; suffix K/M/G recognized [768M]

Usage:   samtools view [options] <in.bam>|<in.sam> [region1 [...]]

Options: -b       output BAM
         -h       print header for the SAM output
         -H       print header only (no alignments)
         -S       input is SAM
         -u       uncompressed BAM output (force -b)
         -1       fast compression (force -b)
         -x       output FLAG in HEX (samtools-C specific)
         -X       output FLAG in string (samtools-C specific)
         -c       print only the count of matching records
         -B       collapse the backward CIGAR operation
         -@ INT   number of BAM compression threads [0]
         -L FILE  output alignments overlapping the input BED FILE [null]
         -t FILE  list of reference names and lengths (force -S) [null]
         -T FILE  reference sequence file (force -S) [null]
         -o FILE  output file name [stdout]
         -R FILE  list of read groups to be outputted [null]
         -f INT   required flag, 0 for unset [0]
         -F INT   filtering flag, 0 for unset [0]
         -q INT   minimum mapping quality [0]
         -l STR   only output reads in library STR [null]
         -r STR   only output reads in read group STR [null]
         -s FLOAT fraction of templates to subsample; integer part as seed [-1]
         -?       longer help

[M::bwa_idx_load_from_disk] read 0 ALT contigs
make: *** [/home/hsiang/miniconda3/envs/Python3_6/bin/share/tigmint-1.2.4-0/bin/tigmint-make:191: myassembly.myreads.sortbx.bam] Error 1

----------------------------------------------------------------

**Comment by lcoombe** [comment]
HI @ClarenceHsiang,

Could you report the version of `samtools` that you are using? (With `samtools --version`) Also, could you double check that you are using your conda installat ion of `samtools`? (With `which samtools`)
At first glance, it looks like you could be using an older version of `samtools` which is missing some of the options in newer versions.

Thank you for your interest in Tigmint!
Lauren

**Comment by ClarenceHsiang** [comment]
Dear Tigmint Team:
Good morning.
Sorry for the late replay.
The samtools version is Version: 0.1.19-44428cd by using conda.

-------
Program: samtools (Tools for alignments in the SAM format)
Version: 0.1.19-44428cd

**Comment by lcoombe** [comment]
Hi @ClarenceHsiang,

Could you try updating your `samtools` to a later version? Ex. `1.15`? Looking at the `samtools` release notes, the `-t` parameter was introduced in version 1.5 in 2017, so any version newer than that should work.
