### ISSUE TITLE
Using MinION reads

### ISSUE THREAD

**Issue by asdcid** [bcgsc/tigmint#11]
Hi Shaun,

I am Raymond, a student of Robert. Robert has asked you whether it is possible to run tigmint with MinION reads in twitter, and you suggested that:"I haven't tested it, but you ought to be able to use Tigmint with long reads. Map reads to the assembly with e.g. minimap2, convert the PAF file to BED, then run tigmint-cut.". I have successfully run tigmint-cut, but could you give me some hints how to run the "scaffold" step after corrected misassemblies?

Thank you very much,
Raymond

**Comment by lcoombe** [comment]
Hello Raymond,
The Tigmint Makefile uses ARCS for scaffolding, which utilizes linked reads. Were you wanting to scaffold your assembly post-Tigmint with the MinION reads or linked reads?

**Comment by asdcid** [comment]
Hi Icoombe,
MinION data, I don't have linked reads. It seems that I can't rescaffold my assembly with MinION.

**Comment by lcoombe** [comment]
Hi Raymond,
Although ARCS (which is the scaffolder used in the Tigmint Makefile) uses linked reads, you look at using a scaffolder designed for long reads, such as LINKS (https://github.com/bcgsc/LINKS) after breaking your assembly with Tigmint.

**Comment by roblanf** [comment]
@asdcid didn't you also notice that TIGMINT seems to cut assemblies at homopolymers with MinION reads? 

My guess here is that the homopolymer errors in MinION reads lead to dramatic-looking drops in coverage at one end of a homopolymer run (depends on how the aligner works, but they usually bunch all the bases up at one end or another), and that this might be throwing TIGMINT off. 

We wondered if this is something that could be addressed by just adding in an expectation that one would see coverage dropoffs around homopolymers. (Also I this might be a separate issue).

**Comment by sjackman** [comment]
Which aligner did you use with your MinION reads, and have you tried Minimap2? It should be able to align through simple sequence repeats. You may want to try increasing the chaining parameter `-r`.
