### ISSUE TITLE
yet another "make: *** No rule to make target" issue

### ISSUE THREAD

**Issue by salvatierra8** [bcgsc/tigmint#116]
Greetings,

First of all, sorry for opening another thread about previously posted issues, but after trying several times, i can't use tigmint. So, to be precise i actually installed longstitch through conda command and created a sole enviroment for this tool, i haven't been able use it, that's why i decided to use tigmint alone with no luck either.
This is the comand i used (taking longmap=pb out makes no difference)
tigmint-make tigmint longmap=pb draft=assembly1 reads=H1_1

And get this message back

make: *** No rule to make target 'assembly1.H1_1.sortbx.bam', needed by 'assembly1.H1_1.as0.65.nm5.molecule.size2000.dist50000.bed'.  Stop.

From what i understand after reading similar issues, the problem was that the command was not being run in the working directory, _which my Windows derived n00b bioinformatic brain understand as the directory where the files are_, however the problem still persist.

And this directory looks like this: (longstitch) salvatierra@salvatierra-FXZR:~/Documents/Secuencias/PacBio$ 

I would appreciate your help. Thanks in advance.

**Comment by lcoombe** [comment]
Hello @salvatierra8,

It looks like you are trying to use `tigmint-long` (Ie. inputting long reads to correct `assembly1.fa`)? In that case you need to specify the `tigmint-long` target.
Ie:
```
tigmint-make tigmint-long longmap=pb draft=assembly1 reads=H1_1
```
There is more information about tigmint-long and how to use it here: https://github.com/bcgsc/tigmint#usage

I hope that helps  - thanks for your interest in Tigmint!
Lauren

**Comment by salvatierra8** [comment]
No, I still get the error with a few changes to the error message:

make: *** No rule to make target 'assembly1.fa', needed by 'assembly1.H1_1.cut500.molecule.size2000.dist50000.bed'.  Stop.

**Comment by lcoombe** [comment]
Could you provide the full log, as well as the command?

**Comment by salvatierra8** [comment]
It's running! ... It never crossed my mind that the extension would need to be as described in the code tag, until you empathized in the previous comment, as i understood that fasta=fa=fna, and in a similar way the gzip versions. I had my files named like assemble1.fasta and H1.fasta.gz . Thanks for your help!

**Comment by lcoombe** [comment]
Excellent - very glad to hear that it's working now!
