### ISSUE TITLE
tigmint-make errors

### ISSUE THREAD

**Issue by macarima** [bcgsc/tigmint#12]
Hello.

When I execute 'tigmint-make', I got some errors like below.

```
macarima@localhost:~$ tigmint-make
make: command: Command not found
make: command: Command not found
make: command: Command not found
Tigmint: Correct misassemblies using linked reads
Usage: tigmint-make [COMMAND]... [PARAMETER=VALUE]...
Example: tigmint-make tigmint draft=myassembly reads=myreads
For more information see https://bcgsc.github.io/tigmint/
```

How can I remove these errors?

**Comment by fbemm** [comment]
The make files is using shell commands in some parts. If you work on Ubuntu there is no shell by default. The errors don't break tigmint. In case you still want to get rid of them replace all appearances of `shell command -v ` with `which`.

**Comment by lcoombe** [comment]
Thanks @fbemm!

**Comment by macarima** [comment]
Thank you :^) @fbemm
