### ISSUE TITLE
tigmint compilation issue

### ISSUE THREAD

**Issue by ferreirafm** [bcgsc/tigmint#123]
Hi devs, 
How do I have to set the btllib so as can compile tigmint?
The btllib was successfully compiled:
#########
 mephisto:/usr/local/programs/btllib/install> tree -L 2
.
├── bin
│   └── indexlr
├── include
│   └── btllib
└── lib
    ├── btllib
    ├── _btllib.so -> /usr/local/programs/btllib/install/lib/btllib/python/btllib/_btllib.so
    ├── __init__.py -> /usr/local/programs/btllib/install/lib/btllib/python/btllib/__init__.py
    └── libbtllib.a
###########

Before compile tigmint I set:
export LDFLAGS="-L /usr/local/programs/btllib/include/btllib -lbtllib $LDFLAGS"

And tigmint compilation issue:
mephisto:/usr/local/programs/tigmint> make -C src
make: Entering directory '/usr/local/programs/tigmint/src'
g++ -o long-to-linked-pe long-to-linked-pe.cpp -O3 -Wall -Werror -Wno-unknown-pragmas -std=c++11 -pthread -L /usr/local/programs/btllib/install/lib -lbtllib  -l btllib
long-to-linked-pe.cpp:1:10: fatal error: btllib/seq_reader.hpp: No such file or directory
    1 | #include "btllib/seq_reader.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Any clues are apreciated.

**Comment by lcoombe** [comment]
Hi @ferreirafm,

Apologies for the delayed response - I was on vacation.

I'd recommend installing tigmint using conda if possible - it just makes installation smoother, so you don't have to worry about dependencies. 

If you need to compile tigmint from source, take a look at this section of the btllib README - https://github.com/bcgsc/btllib#using-the-library. Have you also run the `CPPFLAGS` export command?

Thank you for your interest in Tigmint!
Lauren

**Comment by ferreirafm** [comment]
That was what I did?
Thanks for helping.
