### ISSUE TITLE
myassembly.myreads.as0.65.nm5.molecule.tsv in null

### ISSUE THREAD

**Issue by shameem356** [bcgsc/tigmint#13]
Hello,

I am running tigmint with the following command.But **myassembly.myreads.as0.65.nm5.molecule.tsv** file is coming as null.Please can  let me know the reason ?

tigmint-make tigmint draft=myassembly reads=myreads t=16

**Comment by lcoombe** [comment]
Hello, 
Could you provide the list of files in your working directory (```ls -lah```), and the log produced by tigmint? Were there any errors generated?

**Comment by shameem356** [comment]
Below are the list of files from working directory.There were no error messages generated.

myassembly.fa
myassembly.fa.amb
myassembly.fa.ann
myassembly.fa.bwt
myassembly.fa.fai
myassembly.fa.pac
myassembly.fa.sa
myassembly.myreads.as0.65.nm5.molecule.bed
myassembly.myreads.as0.65.nm5.molecule.size2000.bed
myassembly.myreads.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.fa
myassembly.myreads.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.fa.bed
myassembly.myreads.as0.65.nm5.molecule.tsv
myassembly.myreads.bam
myassembly.myreads.sam
myassembly.myreads.sortbx.bam
myassembly.tigmint.fa
myreads.fq.gz
nohup.out
old_nohup.sh
out.txt
run_bwa.sh
run_tigmint.sh
----------------------------
These are the tail part of log file.

/data/labs/genomics_lab/shared/shameem/apps/tigmint/bin/tigmint-molecule -b myassembly.myreads.sortbx.bam -o myassembly.myreads.as0.65.nm5.molecule.tsv -a 0.65 -n 5 -q 0 -d 50000
awk 'NR>1 { print $1"\t"$2-1"\t"$3-1"\tReads="$7",Size="$4",Mapq="$8",AS="$9",NM="$10",BX="$5",MI="$6"\t"$7 }' myassembly.myreads.as0.65.nm5.molecule.tsv \
        | sort -k1,1 -k2,2n -k3,3n >myassembly.myreads.as0.65.nm5.molecule.bed
awk '$3 - $2 >= 2000' myassembly.myreads.as0.65.nm5.molecule.bed >myassembly.myreads.as0.65.nm5.molecule.size2000.bed
samtools faidx myassembly.fa
/data/labs/genomics_lab/shared/shameem/apps/tigmint/bin/tigmint-cut -p16 -w1000 -n20 -t0 -o myassembly.myreads.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.fa myassembly.fa myassembly.myreads.as0.65.nm5.molecule.size2000.bed
Started at: 2018-05-17 16:12:50.703750
Reading contig lengths...
Finding breakpoints...
Cutting assembly at breakpoints...
DONE!
Ended at: 2018-05-17 16:12:57.061767
ln -sf myassembly.myreads.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.fa myassembly.tigmint.fa

**Comment by lcoombe** [comment]
Ok thanks -- can you also provide a few lines of the myassembly.myreads.sortbx.bam file? (Just with ```samtools view```)

**Comment by shameem356** [comment]
By mistake I closed the ticket.Please can you open it.

**Comment by lcoombe** [comment]
It looks like you don't have the barcode in the BX tag in those alignments. Tigmint expects the barcode to be in the ```BX:Z``` tag of the alignments, and will sort the alignment file by this tag. Make sure your chromium reads have the "BX:Z" tag in the comment of the read header:
Ex:
```
@E00316:145:HMVG3CCXX:5:1214:6786:3014 BX:Z:AAACACCAGACAATAC-1
TCTGTCTCTCTGTCCATCTCTGTCTTTCTATGTCTGTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCTCCCTGTGCCTCTCCCCCCCCCCCCCCCCTCGTCCTTCCCCTCTCCGCCTTCCCCC
+
FAAFAKKKFKKKKFFAAF<AFKF,FFA<FKKAKFKK<AFKFKKKK77F,F7FFFKF<<AF,A,AFAFKKKAFFF,,,,,,,7,7,,7,<<FA,(AAA(,AA(((,,,,,,,,,,(,,,7(((,,,7,7
@E00316:145:HMVG3CCXX:5:1214:6786:3014 BX:Z:AAACACCAGACAATAC-1
AAATGGACAGAGAGAGAAACAGACAGACAGGGAGGGAGGGAGGGGGGCGAGACGGGGGGGGGGAGGGAGGGGGGGAGGGAGGGAGGGGGAGAGACAGAAATAGAGAGAGAGAGAGGGAGAGAGAGAGAGAGAGAAGGGTGGTGGGTGGTGT
+
AAFFFKKKKKKKKKKKKKKKKKKKKKFKKKKKKKKKAFKKF<AF,(,(((<,,,,(((,(,(((,(,,,(,(,,<(,<A,7(,,7(,((,,,,,,7,,7F,,,,,<,7,,A,,,,,,,,<FF<,,,,,<FF<F7,,,,7,,,,,,,,7,7,
```
This is the format produced by longranger basic.

**Comment by shameem356** [comment]
Thanks for your help. it is working now.
