### ISSUE TITLE
Runtime on finding breakpoints

### ISSUE THREAD

**Issue by JordideRaad** [bcgsc/tigmint#14]
Dear Shaun Jackman,

We have recently received our 10x genomics data and currently optimizing our de novo assembly using different tools (bird genome of 1.2GB). To check for assembly errors, I decided to run Tigmint. The mapping step proved to be no problem, however the "finding breakpoints" step in which tigmunt-cut is used, is now running for more than two weeks without anything happening. 

Is it expected that this step takes so much time?

Kind regards,

Jordi

**Comment by lcoombe** [comment]
Hi Jordi,

No, the tigmint-cut step is not expected to take that long. Try using our most recent release (1.1.1) --  1.1.0 has a significant bug which can cause the tigmint-cut step to take much longer and not cut properly.  
For reference, when running tests using a human assembly and setting ```t=16```, this step usually completes in less than 10 minutes.

Hope that helps!
Lauren

**Comment by JordideRaad** [comment]
Dear Lauren,

Thank you very much for the notification. I ran the analyses again today with the new verstion. Indeed, in the newest version tigmint-cut seems to work now.  

Kind regards,

Jordi

**Comment by lcoombe** [comment]
Hi Jordi,

That's great - I'm glad Tigmint is running properly for you now!

Lauren
