### ISSUE TITLE
Scaffolds output tigmint-arcs error

### ISSUE THREAD

**Issue by JordideRaad** [bcgsc/tigmint#15]
Dear Shaun and Lauren,

Thanks to your advice concerning the tigmint-cut update, I was able to make tigmint work and locate possible mis-assemblies in my scaffold file. However, when trying to re-scaffold my broken assembly with tigmint arcs, I get and error message when the program is trying to write the final scaffold file:

[stderr_arcs.txt](https://github.com/bcgsc/tigmint/files/2047661/stderr_arcs.txt)

Nevertheless, the run output seems fine:

[stdout_arcs.txt](https://github.com/bcgsc/tigmint/files/2047662/stdout_arcs.txt)

Any idea what might have caused this error? I cant seem to figure it out. 

It might be that this is related to the dependency of Links, as brew install links-scaffolder was not available, and I had to install the related dependencies of ARCS individually (https://github.com/bcgsc/arcs)

[brew.txt](https://github.com/bcgsc/tigmint/files/2047586/brew.txt)

Any advice is highly appreciated.

Kind regards,

Jordi de Raad

**Comment by lcoombe** [comment]
Also - Just so you know, I'm out of the office from this afternoon to the end of the week, but hopefully @sjackman will have time to help you troubleshoot!

**Comment by sjackman** [comment]
```
/home/jderaad/softwares/conda/anaconda3/envs/tigmint/bin/LINKS [v1.8.4] terminated successfully on Mo 28. Mai 22:46:11 CEST 2018
make: *** [N15Minsize50000.barcoded.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.barcoded.c5_e30000_r0.05.arcs.a0.1_l10.links.scaffolds.fa] Error 255
```
I see that you're running LINKS 1.8.4, and that's also the most recent version in Brewsci/science. LINKS had a bug wherein it would return failure (exit status 255) even though it had in fact succeeded, which caused `make` to believe that LINKS had failed. I'll package LINKS 1.8.6 for Brewsci/bio. In the mean time, you could install LINKS 1.8.6 manually from https://github.com/bcgsc/LINKS/releases

**Comment by sjackman** [comment]
LINKS 1.8.5 is now in Brewsci/bio, which should resolve this issue.
```sh
brew update
brew tap brewsci/bio
brew upgrade links-scaffolder
```
Thanks again for the bug report, @JordideRaad !

**Comment by JordideRaad** [comment]
Dear Shaun and Lauren,

Thank you again for the amazing support so far. Indeed, removing the old version of links (1.8.4) and installing the dependency as Shaun mentioned works now. 

I only got one slight error at the final step, stating that the gsed command was not found. I could easily fix this with brew install gnu-sed. 

Thanks again for all the support!

Kind regards,

Jordi

**Comment by sjackman** [comment]
I've committed https://github.com/bcgsc/tigmint/commit/b98bf28ce72a06cffcfe47dfab0c2dd6bf088542 just now to fix the `gsed` issue. Thanks for the bug report!
