### ISSUE TITLE
Can I get the breakpoint information?

### ISSUE THREAD

**Issue by luyang93** [bcgsc/tigmint#22]
In tigmint-cut,I got function printBreakpoints().
In the output file,draft.tigmint.fa.bed,I guess scaffold_8-1/2/3 are breakpoints.
Is this right?

**Comment by luyang93** [comment]
scaffold_8	0	3877166	scaffold_8-1
scaffold_8	3877166	3881691	scaffold_8-2
scaffold_8	3881691	5693785	scaffold_8-3

**Comment by lcoombe** [comment]
@luyang93 - Yes, the ```breaktigs.fa.bed``` bedfile describes where tigmint cut the input scaffolds. 
In this case, there were 2 breakpoints in scaffold_8 which resulted in the scaffold being in 3 pieces.

Here's another example:
```
scaffold449     0       589742  scaffold449-1
scaffold449     589742  590109  scaffold449-2
scaffold449     590109  1405264 scaffold449-3
scaffold513     0       1123641 scaffold513
```
Here, scaffold513 was not cut, while scaffold449 was cut in 2 places (indicated by the coordinates in the bedfile) to yield 3 pieces.
