### ISSUE TITLE
recipe for target 'merged.barcoded.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.barcoded.sortn.bam' failed

### ISSUE THREAD

**Issue by ewafula** [bcgsc/tigmint#27]
tigmint-make fails after running for a day. I am not sure exactly how to deal with the error.

########################### run log #####################

[main] CMD: bwa mem -t50 -pC merged.fa barcoded.fq.gz
[main] Real time: 19582.030 sec; CPU: 744783.844 sec
[bam_sort_core] merging from 400 files and 50 in-memory blocks...
/usr/local/bin/tigmint-molecule -a0.65 -n5 -q0 -d50000 -s2000 merged.barcoded.sortbx.bam | sort -k1,1 -k2,2n -k3,3n >merged.barcoded.as0.65.nm5.molecule.size2000.bed
samtools faidx merged.fa
/usr/local/bin/tigmint-cut -p50 -w1000 -n20 -t0 -o merged.barcoded.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.fa merged.fa merged.barcoded.as0.65.nm5.molecule.size2000.bed
Started at: 2019-03-04 01:32:53.356125
Reading contig lengths...
Finding breakpoints...
Cutting assembly at breakpoints...

Tool:    bedtools getfasta (aka fastaFromBed)
Version: v2.21.0
Summary: Extract DNA sequences into a fasta file based on feature coordinates.

Usage:   bedtools getfasta [OPTIONS] -fi <fasta> -bed <bed/gff/vcf> -fo <fasta>

Options:
        -fi     Input FASTA file
        -bed    BED/GFF/VCF file of ranges to extract from -fi
        -fo     Output file (can be FASTA or TAB-delimited)
        -name   Use the name field for the FASTA header
        -split  given BED12 fmt., extract and concatenate the sequencesfrom the BED "blocks" (e.g., exons)
        -tab    Write output in TAB delimited format.
                - Default is FASTA format.

        -s      Force strandedness. If the feature occupies the antisense,
                strand, the sequence will be reverse complemented.
                - By default, strand information is ignored.

        -fullHeader     Use full fasta header.
                - By default, only the word before the first space or tab is used.

DONE!
Ended at: 2019-03-04 01:55:48.834468
bwa index merged.barcoded.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.fa
[bwa_index] Pack FASTA... 0.00 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.00 seconds elapse.
[bwa_index] Update BWT... 0.00 sec
[bwa_index] Pack forward-only FASTA... 0.00 sec
[bwa_index] Construct SA from BWT and Occ... 0.00 sec
[main] Version: 0.7.10-r789
[main] CMD: bwa index merged.barcoded.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.fa
[main] Real time: 0.247 sec; CPU: 0.004 sec
bwa mem -t50 -pC merged.barcoded.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.fa barcoded.fq.gz | samtools view -@50 -h -F4 -o merged.barcoded.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.barcoded.sortn.bam
[M::main_mem] read 3610110 sequences (500000235 bp)...
bash: line 1:  2396 Segmentation fault      bwa mem -t50 -pC merged.barcoded.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.fa barcoded.fq.gz
      2397 Done                    | samtools view -@50 -h -F4 -o merged.barcoded.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.barcoded.sortn.bam
/usr/local/bin/tigmint-make:215: recipe for target 'merged.barcoded.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.barcoded.sortn.bam' failed
make: *** [merged.barcoded.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.barcoded.sortn.bam] Error 139
make: *** Deleting file 'merged.barcoded.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.barcoded.sortn.bam'
[ekw10@debruijn tigmint]$

**Comment by lcoombe** [comment]
Hi @ewafula ,

Could you please enclose copy-and-paste blocks in triple back ticks? Using that formatting will make your pasted commands much easier to read.
(https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code)

It looks like the error you are getting in ```tigmint-cut``` is very similar to what a user saw in a previous issue reported in the ARCS repo: https://github.com/bcgsc/arcs/issues/48
Try using a newer version of ```bedtools``` - I use ```v2.27.1``` and don't get any errors.

Hope that helps!
Lauren
