### ISSUE TITLE
"No rule to make target"

### ISSUE THREAD

**Issue by dcopetti** [bcgsc/tigmint#3]
Hi,
After running successfully longranger 
`longranger basic --id=4606 --fastqs=input_fastqs --localcores=4 --localmem=30 `
I am running tigmint-span but I am getting this error:
```
[copettid@kp141-242 tigmint]$ ~/bin/tigmint/tigmint-make tigmint
make: *** No rule to make target 'draft.reads.as0.65.nm5.molecule.tsv', needed by 'tigmint'.  Stop.
```
I had to rename the .fastq.gz to fq.gz file, and the rest seems fine to me:
```
[copettid@kp141-242 tigmint]$ ~/bin/tigmint/tigmint-make help
Tigmint: Correct misassemblies using linked reads
Usage: tigmint-make [COMMAND]... [PARAMETER=VALUE]...
Example: tigmint-make tigmint draft=myassembly reads=myreads
For more information see https://bcgsc.github.io/tigmint/
[copettid@kp141-242 tigmint]$ ls
4606  input_fastqs  Rabiosa_genome.fa
[copettid@kp141-242 tigmint]$ ls 4606/outs/
barcoded.fq.gz  summary.csv
```
I am wondering if I should have that .tsv file created at some point. Or what is the reason for this issue?
Thanks,
Dario

**Comment by lcoombe** [comment]
Hi Dario,

To use tigmint, your command should look something like this:
`tigmint-make tigmint draft=myassembly reads=myreads`

In this example, tigmint would expect to find a draft assembly myassembly.fa and chromium reads (post-longranger) myreads.fq.gz in your current working directory.

For your case, I would make a soft link to your barcoded.fq.gz reads file in your 'tigmint' directory, and run the command:
`tigmint-make tigmint draft=Rabiosa_genome reads=barcoded`

That should produce a molecule TSV file like you mentioned above, and a number of other output files.

Let me know if that helps!
Lauren

**Comment by dcopetti** [comment]
Hi Lauren,
Thanks for the suggestion, with the symlink it works now (I also did not paste the whole command).
Dario

**Comment by lcoombe** [comment]
Great - I'm glad you got it working!
