### ISSUE TITLE
Changing /tmp location

### ISSUE THREAD

**Issue by ilaydabozan** [bcgsc/tigmint#34]
Hello, I'm running `tigmint-make tigmint draft=myassembly reads=myreads` command in ORCA docker environment. I got this error;

```[E::bgzf_flush] File write failed (wrong size)
[E::bgzf_close] File write failed
[E::bgzf_flush] File write failed (wrong size)
[E::bgzf_close] File write failed
[E::bgzf_flush] File write failed (wrong size)
[E::bgzf_close] File write failed
[E::bgzf_flush] File write failed (wrong size)
[E::bgzf_close] File write failed
samtools sort: failed to create temporary file "/tmp/myassembly.myreads.sortbx.bam.PVwtv6.0136.bam": No space left on device
samtools sort: failed to create temporary file "/tmp/myassembly.myreads.sortbx.bam.PVwtv6.0137.bam": No space left on device
```

I believe this is due to my filesystem not having enough memory in the `/tmp` directory. Is there a way to reassign the temporary directory to another location?

Thank you,
Ilayda

**Comment by lcoombe** [comment]
Hi Ilayda,

Try setting your `TMPDIR` variable (ie. `export TMPDIR=<other dir>`). That should lead the temporary files to be created in the directory of your choice vs. in `/tmp` by default.

Hope that helps!
Lauren

**Comment by ilaydabozan** [comment]
Thank you so much, Lauren, for the quick response.
I will try it out shortly and let you know.

Best,
Ilayda

**Comment by ilaydabozan** [comment]
Hi Lauren,

Thank you for your response. I was able to change the `TMPDIR` to a directory with more memory allocations and Tigmint ran perfectly fine. 

Best,
Ilayda

**Comment by lcoombe** [comment]
Excellent - I'm glad that fixed the issue!
