### ISSUE TITLE
make: *** No rule to make target `***.as0.65.nm5.molecule.tsv', needed by `tigmint'.  Stop.

### ISSUE THREAD

**Issue by QiushiLi** [bcgsc/tigmint#4]
Hi Shaun,

I'm trying to use tigmint to correct misassemblies with 10x linked-reads (barcoded.fastq.gz, generated from the longranger basic). There is a immediate make error after "tigmint tigmint"
make: *** No rule to make target `***.as0.65.nm5.molecule.tsv', needed by `tigmint'.  Stop.
Here are the exact command lines I typed. 

1, tigmint installation
git clone https://github.com/bcgsc/tigmint && cd tigmint

2, dependencies installation with a new environment “tigmint3” in conda, python3.6.4 was used
$source activate /path/to/anaconda3/envs/tigmint3
$pip install intervaltree
$pip install pybedtools
$pip install statistics
$pip install pysam (actually pysam was already installed as a dependency of pybedtools)

3, must-have software installation with linuxbrew
$brew install pigz gawk gnu-sed graphviz makefile2graph miller samtools bedtools bwa

4, r and r-packages installation with conda (brew failed due to missing xml2, couldn't be solved in short time)
$conda install R
$conda install -c r r-essentials (”ggplot2", "rmarkdown", "tidyverse" are all included)
$Rscript -e 'install.packages(c("uniqtag"), repos = c(CRAN = "https://cran.rstudio.com"))'

5, tigmint command line

test_1
$tigmint tigmint draft=barcoded_pilon_falcon6unzip reads=barcoded
make: *** No rule to make target `barcoded_pilon_falcon6unzip.barcoded.as0.65.nm5.molecule.tsv', needed by `tigmint'.  Stop.
test_2
$tigmint tigmint draft=barcoded_pilon_falcon6unzip.fa reads=barcoded.fastq.gz
make: *** No rule to make target `barcoded_pilon_falcon6unzip.fa.barcoded.fastq.gz.as0.65.nm5.molecule.tsv', needed by `tigmint'.  Stop.

no output

Just let me know if you need more information!

Best,
Qiushi

**Comment by QiushiLi** [comment]
additional information on homebrew/science
$brew tap homebrew/science
Error: homebrew/science was deprecated. This tap is now empty as all its formulae were migrated.

"This tap was deprecated because it had different goals from the wider Homebrew organisation (e.g. Linuxbrew CI/support). All widely used, buildable formulae were migrated to homebrew/core."

In my case, homebrew/core was tapped when install the latest linuxbrew.

**Comment by lcoombe** [comment]
Hi Qiushi,

Could you confirm the names of your draft assembly and chromium reads files?

In this example command, tigmint expects to find a draft assembly myassembly.fa and chromium reads (post-longranger) myreads.fq.gz in your current working directory:
`tigmint-make tigmint draft=myassembly reads=myreads`

Lauren

**Comment by QiushiLi** [comment]
Hi Lauren,

I renamed the two input files and it works now! Much appreciated.
$tigmint tigmint draft=draft reads=reads

Qiushi

**Comment by lcoombe** [comment]
Great! I'm glad it's working for you now!
