### ISSUE TITLE
tigmint-make tigmint error

### ISSUE THREAD

**Issue by wjj666** [bcgsc/tigmint#44]
Hello, I run this command:
tigmint-make tigmint draft=*/ontas_racon1_pilon1 reads=*/10x

The error information is：
make: *** No rule to make target '*/ontas_racon1_pilon1.*/10x.as0.65.nm5.molecule.size2000.trim0.window1000.span20.breaktigs.fa', needed by 'tigmint'.  Stop.

Could you please tell me how to solve this problem? Thank you very much.

**Comment by lcoombe** [comment]
Hello @wjj666,

I'm assuming your reads are named `10x.fq.gz` and the draft `ontas_racon1_pilon1.fa`?
If so, you need to take out those spare slashes that you have in the command, which sort of look like a file path:
```
tigmint-make tigmint draft=ontas_racon1_pilon1 reads=10x
```
Ensure that the draft and reads files are in the current working directory, and make soft-links to achieve that if neccessary.

Hope that helps - Thank you for your interest in Tigmint!
Lauren
