### ISSUE TITLE
Error : no progress of scaffolding running

### ISSUE THREAD

**Issue by kishore556** [bcgsc/tigmint#52]
Hello
I run the tigmint program with draft assembly in different folder and Nanopore reads library. The program get stuck-up at showing following output producing only the file "NFCC4014.fastq.gz.cut500.fq.gz". for hours and hours the thiis sinlge file size remain 50.5mb not further addition or progress. I kill the program by using Ctrl+C, it shows error and the output file generated is deleted automatically. I dont understand whats the problem? Why the tigmint program stop and dont proceed further. All other dependency tools are installed.

acer@kishor:~/talasmbly$ tigmint-make tigmint-long draft=4spd2403.fa reads=/home/acer/oxford/NFCC4014.fastq.gz span=auto G=33000000 dist=auto longmap=ont t=12
Program run:
pigz -p12 -dc  | /home/linuxbrew/.linuxbrew/Cellar/tigmint/1.2.2/libexec/bin/long-to-linked -l500 -m2000 -g33000000 -s -d -o /home/acer/oxford/NFCC4014.fastq.gz.tigmint-long.params.tsv | pigz -p12 > /home/acer/oxford/NFCC4014.fastq.gz.cut500.fq.gz

Kinldy provide me solution. I have draft assembly by CANU, Flye of Nanopore data and draft assembly of Illumina reads by SPAdes software. How ca I input the Illumina paired reads presnt in 4 files (2 sets) as: 1F.fq, 1R.fq, 2F.fq and 2R.fq.

**Comment by lcoombe** [comment]
Hi @kishore556 ,

A couple of issues I see with your command (More details here: https://github.com/bcgsc/tigmint#usage):
* Make sure all of your input files are in your current working directory - don't use the full paths. You can use soft-links to do this if needed
* Do not include the file suffixes for the assembly, reads in the command

So for your command:
```
ln -s /home/acer/oxford/NFCC4014.fastq.gz NFCC4014.fq.gz
tigmint-make tigmint-long draft=4spd2403 reads=/home/acer/oxford/NFCC4014 span=auto G=33000000 dist=auto longmap=ont t=12
```
I'm not sure I understand your question about the Illumina PE reads - are they linked reads? You can run Tigmint using long reads (as you have in your command above), or using linked reads.

Thank you for your interest in Tigmint!
Lauren

**Comment by kishore556** [comment]
thanks Lauren,
It worked well with Long reads correcting miss-assembly of short read generated by SPAdes. 
How should I proceed with short reads illumina PE reads? As PE reads are in multiple files. I couldn't  understand from usage portion of tigmint page. Shall I need to pass the read alignment sorted .bam file at option "reads= ....." . Please guide.

**Comment by lcoombe** [comment]
Hi Kishor,

Glad to hear that Tigmint worked well for you with correcting the SPAdes assembly using long reads!

Are you hoping to correct the assembly with another round of Tigmint, using short reads? Are they linked reads? 
Just to be clear, Tigmint only uses linked reads (not regular Illumina PE reads) for misassembly correction in that mode. If your files are in fact linked reads, I would recommend concatenating all of the separate files together, and specifying the read file with `reads` in the tigmint command, similar to how you did it for the long reads.
Ex. if your read file is named `linked_reads.fq.gz`, `reads=linked_reads`

Hope that helps!
Lauren

**Comment by kishore556** [comment]
Thanks Lauren,
Unfortunately,  short reads are PE. I must go for another option to scaffold the Long Read Assembly by short PE. 
Thanks again.
Kishor

**Comment by lcoombe** [comment]
Hi Kishor,

Yes, unfortunately Tigmint only works for breaking misassemblies in the draft genome using linked (short) or long reads.
If you are looking to scaffold an assembly using regular PE short reads, you could take a look at the scaffolding step of ABySS.

Good luck!
Lauren
