### ISSUE TITLE
src/long-to-linked-pe v1.0: Using more than 6 threads does not scale, reverting to 6.

### ISSUE THREAD

**Issue by mmokrejs** [bcgsc/tigmint#67]
The README.md claims one can run tigmint with any number of threads.

It turn out the maximum at least in some step is just 6:

`long-to-linked-pe v1.0: Using more than 6 threads does not scale, reverting to 6.`

Please update the `t=8: Number of threads` line in README.md accordingly explaining what steps will not use multiple CPUs. I guess one still want to use for for the `bwa` step but who knows.

**Comment by lcoombe** [comment]
Hi @mmokrejs - we have added targets for the various steps of Tigmint in 8eb4f7f (Thanks @PuneetSS!).
They are documented in the README if you're interested in using them!
